# Generated by Django 4.1.7 on 2023-03-14 08:41

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_title', models.CharField(max_length=255)),
                ('faculty_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_title', models.CharField(max_length=255)),
                ('major_description', models.TextField()),
                ('major_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unik_title', models.CharField(max_length=255)),
                ('unik_description', models.TextField()),
                ('unik_date_created', models.DateField(auto_now_add=True)),
                ('unik_study_type', models.CharField(max_length=255)),
                ('unik_lang', models.CharField(max_length=255)),
                ('unik_img', models.ImageField(blank=True, default=api.models.default_image, upload_to='images/')),
                ('unik_logo', models.ImageField(blank=True, default=api.models.default_image, upload_to='images/')),
                ('unik_min_unt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unik_min_ielts', models.DecimalField(decimal_places=1, max_digits=4)),
                ('unik_student_num', models.PositiveIntegerField()),
                ('unik_study_year_num', models.PositiveIntegerField()),
                ('unik_location', models.CharField(max_length=255)),
                ('unik_website', models.URLField()),
                ('unik_tuition', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unik_admission_criteria', models.TextField()),
                ('unik_student_life', models.TextField()),
                ('unik_campus_housing', models.TextField()),
                ('unik_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
                ('unik_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.major')),
            ],
        ),
    ]
